export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD'

export const FETCHING_STARTED = 'FETCHING_STARTED'
export const UPDATE_TRACK_LIST = 'UPDATE_TRACK_LIST'
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS'
export const FETCHING_ERROR = 'FETCHING_ERROR'

export const EXPAND_TRACK = 'EXPAND_TRACK'
export const COLLAPSE_TRACK = 'COLLAPSE_TRACK'